#!/usr/bin/env python3
"""RLE-compress three BWR dual-planes into one CC2510 image blob (EXP-050)."""
from __future__ import annotations

import re
from pathlib import Path

PLANE = 5624
UART = Path(__file__).resolve().parents[1] / "firmware" / "OpenVusion26_GU140_FW_UART_DIAG"
OUT = UART / "v0.10e_nfc_show3"

SOURCES = (
    ("ovh", UART / "v0.4l_ovhack" / "img_ovhack.c"),
    ("tst", UART / "v0.9e_nfc_bwrtest" / "img_ovhack.c"),
    ("su", UART / "v0.9d_nfc_show4" / "img_ovhack.c"),
)


def parse_planes(path: Path) -> tuple[bytes, bytes]:
    nums = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", path.read_text(encoding="ascii"))]
    if len(nums) < 2 * PLANE:
        raise SystemExit(f"{path} too short: {len(nums)}")
    return bytes(nums[:PLANE]), bytes(nums[PLANE : 2 * PLANE])


def rle(data: bytes) -> bytes:
    out = bytearray()
    i = 0
    n = len(data)
    while i < n:
        b = data[i]
        c = 1
        while i + c < n and data[i + c] == b and c < 255:
            c += 1
        out.append(c)
        out.append(b)
        i += c
    return bytes(out)


def unrle(blob: bytes, expect: int) -> bytes:
    out = bytearray()
    i = 0
    while i < len(blob):
        c = blob[i]
        b = blob[i + 1]
        out.extend([b] * c)
        i += 2
    if len(out) != expect:
        raise SystemExit(f"RLE length {len(out)} != {expect}")
    return bytes(out)


def emit_arr(name: str, data: bytes) -> str:
    lines = [f"const unsigned char {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        body = ",".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(data) else ""
        lines.append(f"    {body}{comma}")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    hdr_lines = [
        "#ifndef IMG_RLE_H",
        "#define IMG_RLE_H",
        "#include <stdint.h>",
        f"#define IMG_PLANE {PLANE}u",
    ]
    c_parts = [
        "/* RLE: [count][value] ... count 1..255. Generated by gen_show_rle.py */",
        "#include <stdint.h>",
        '#include "img_rle.h"',
        "",
    ]
    total = 0
    for key, src in SOURCES:
        p10, p13 = parse_planes(src)
        r10, r13 = rle(p10), rle(p13)
        if unrle(r10, PLANE) != p10 or unrle(r13, PLANE) != p13:
            raise SystemExit(f"RLE roundtrip fail {key}")
        total += len(r10) + len(r13)
        print(key, "rle", len(r10), len(r13))
        hdr_lines.append(f"#define {key.upper()}_RLE10_N {len(r10)}u")
        hdr_lines.append(f"#define {key.upper()}_RLE13_N {len(r13)}u")
        hdr_lines.append(f"extern const unsigned char {key}_rle10[];")
        hdr_lines.append(f"extern const unsigned char {key}_rle13[];")
        c_parts.append(emit_arr(f"{key}_rle10", r10))
        c_parts.append("")
        c_parts.append(emit_arr(f"{key}_rle13", r13))
        c_parts.append("")
    hdr_lines.append("#endif")
    (OUT / "img_rle.h").write_text("\n".join(hdr_lines) + "\n", encoding="ascii")
    (OUT / "img_rle.c").write_text("\n".join(c_parts), encoding="ascii")
    print("total rle", total, "out", OUT)


if __name__ == "__main__":
    main()
