#!/usr/bin/env python3
"""Offline 152x296 BWR bitmap -> two 1bpp planes (EXP-033 OpenVusionHack)."""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

WIDTH = 152
HEIGHT = 296
ROW_B = WIDTH // 8
PLANE = HEIGHT * ROW_B  # 5624

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (220, 0, 0)

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "firmware" / "OpenVusion26_GU140_FW_UART_DIAG" / "v0.4l_ovhack"
PREVIEW = ROOT / "captures" / "ov26_exp033_preview.png"


def load_font(size: int) -> ImageFont.FreeTypeFont:
    for name in ("arialbd.ttf", "arial.ttf", "segoeuib.ttf", "segoeui.ttf", "calibrib.ttf"):
        path = Path(r"C:\Windows\Fonts") / name
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default()


def fit_text(draw: ImageDraw.ImageDraw, text: str, max_w: int, start: int) -> ImageFont.FreeTypeFont:
    size = start
    while size >= 12:
        font = load_font(size)
        bbox = draw.textbbox((0, 0), text, font=font)
        if (bbox[2] - bbox[0]) <= max_w:
            return font
        size -= 1
    return load_font(12)


def pack_planes(img: Image.Image) -> tuple[bytearray, bytearray]:
    p10 = bytearray(PLANE)
    p13 = bytearray(PLANE)
    pix = img.load()
    for y in range(HEIGHT):
        for x in range(WIDTH):
            r, g, b = pix[x, y][:3]
            idx = y * ROW_B + (x // 8)
            bit = 7 - (x % 8)
            mask = 1 << bit
            # Nearest of W/B/R
            if r > 160 and g < 80 and b < 80:
                p13[idx] |= mask  # red: p10=0 p13=1
            elif r < 80 and g < 80 and b < 80:
                p10[idx] |= mask  # black: p10=1 p13=0
            # else white: both 0
    return p10, p13


def emit_c_array(name: str, data: bytes) -> str:
    lines = [f"const unsigned char {name}[{PLANE}] = {{"]
    for i in range(0, PLANE, 16):
        chunk = data[i : i + 16]
        body = ",".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < PLANE else ""
        lines.append(f"    {body}{comma}")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    img = Image.new("RGB", (WIDTH, HEIGHT), WHITE)
    draw = ImageDraw.Draw(img)
    margin = 6
    max_w = WIDTH - 2 * margin

    font_ov = fit_text(draw, "OpenVusion", max_w, 28)
    font_hk = fit_text(draw, "Hack", max_w, 48)

    b_ov = draw.textbbox((0, 0), "OpenVusion", font=font_ov)
    b_hk = draw.textbbox((0, 0), "Hack", font=font_hk)
    w_ov, h_ov = b_ov[2] - b_ov[0], b_ov[3] - b_ov[1]
    w_hk, h_hk = b_hk[2] - b_hk[0], b_hk[3] - b_hk[1]
    gap = 24
    total_h = h_ov + gap + h_hk
    y0 = (HEIGHT - total_h) // 2
    x_ov = (WIDTH - w_ov) // 2 - b_ov[0]
    x_hk = (WIDTH - w_hk) // 2 - b_hk[0]
    draw.text((x_ov, y0 - b_ov[1]), "OpenVusion", font=font_ov, fill=BLACK)
    draw.text((x_hk, y0 + h_ov + gap - b_hk[1]), "Hack", font=font_hk, fill=RED)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    img.save(PREVIEW)
    img.save(OUT_DIR / "preview.png")

    p10, p13 = pack_planes(img)
    hdr = (
        "/* Generated by scripts/gen_ovhack_bwr.py -- do not edit by hand. */\n"
        "/* 152x296, 19 B/row, WHITE=00/00 BLACK=10=1 RED=13=1 */\n"
        "#include <stdint.h>\n"
        f"#define IMG_PLANE {PLANE}u\n\n"
    )
    (OUT_DIR / "img_ovhack.c").write_text(
        hdr + emit_c_array("img_p10", p10) + "\n\n" + emit_c_array("img_p13", p13) + "\n",
        encoding="ascii",
    )
    print("preview", PREVIEW)
    print("p10 ones", sum(bin(b).count("1") for b in p10))
    print("p13 ones", sum(bin(b).count("1") for b in p13))
    print("bytes", PLANE)


if __name__ == "__main__":
    main()
